# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Impresso No cart\xe3o')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Impresso No cart\xe3o')),
                ('cardmes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Impresso No cart\xe3o')),
                ('cardano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Impresso No cart\xe3o')),
                ('cvv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Impresso No cart\xe3o')),
            ],
        ),
    ]
