# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cx2site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2',
            name='cardano',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ano Vencimento'),
        ),
        migrations.AlterField(
            model_name='c2',
            name='cardmes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='M\xeas Vencimento'),
        ),
        migrations.AlterField(
            model_name='c2',
            name='cvv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cvv'),
        ),
        migrations.AlterField(
            model_name='c2',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Do Cliente'),
        ),
        migrations.AlterField(
            model_name='c2',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero Impresso No cart\xe3o'),
        ),
    ]
